# Generated by Django 5.2.4 on 2025-07-17 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_day", models.DateField(default=django.utils.timezone.now)),
                ("duration", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "TO DO"),
                            ("IN_PROGRESS", "IN PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("BLOCKED", "BLOCKED"),
                        ],
                        default="TODO",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "epic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="todo.epic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_day", models.DateField(default=django.utils.timezone.now)),
                ("duration", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "TO DO"),
                            ("IN_PROGRESS", "IN PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("BLOCKED", "BLOCKED"),
                        ],
                        default="TODO",
                        max_length=12,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="todo.task",
                    ),
                ),
            ],
        ),
    ]
