# Generated by Django 5.2.4 on 2025-07-18 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_subtask_duration_remove_subtask_start_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="epic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="todo.epic",
            ),
        ),
    ]
